
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase connection configuration
// These values connect to your Supabase project and will work in both
// development and production environments
const SUPABASE_URL = "https://ercsjuuyfyokjgkveeev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyY3NqdXV5Znlva2pna3ZlZWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODYyMDcsImV4cCI6MjA1ODY2MjIwN30.HuJ5uEtQh5DtxZ696sBvSU0K1T7UQYcVIhBs7mwnouM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
